services:
  - type: web
    name: old-eci-dashboard
    env: node
    region: oregon
    plan: free
    buildCommand: "rm -rf node_modules package-lock.json && npm install --production"
    startCommand: "node server.js"
    envVars:
      - key: ECI_PG_DSN
        sync: false
      - key: ECI_DEVICE_TAG
        value: "render"
      - key: NODE_ENV
        value: "production"
